/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as MembersAddRouteImport } from './routes/members/add'
import { Route as EventsAddRouteImport } from './routes/events/add'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as MembersMemberIdIndexRouteImport } from './routes/members/$memberId/index'
import { Route as MembersMemberIdEditRouteImport } from './routes/members/$memberId/edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersAddRoute = MembersAddRouteImport.update({
  id: '/members/add',
  path: '/members/add',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsAddRoute = EventsAddRouteImport.update({
  id: '/events/add',
  path: '/events/add',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdIndexRoute = MembersMemberIdIndexRouteImport.update({
  id: '/members/$memberId/',
  path: '/members/$memberId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdEditRoute = MembersMemberIdEditRouteImport.update({
  id: '/members/$memberId/edit',
  path: '/members/$memberId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/add': typeof EventsAddRoute
  '/members/add': typeof MembersAddRoute
  '/events/': typeof EventsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/members/$memberId/': typeof MembersMemberIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/add': typeof EventsAddRoute
  '/members/add': typeof MembersAddRoute
  '/events': typeof EventsIndexRoute
  '/members': typeof MembersIndexRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/members/$memberId': typeof MembersMemberIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/add': typeof EventsAddRoute
  '/members/add': typeof MembersAddRoute
  '/events/': typeof EventsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/members/$memberId/': typeof MembersMemberIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events/$eventId'
    | '/events/add'
    | '/members/add'
    | '/events/'
    | '/members/'
    | '/members/$memberId/edit'
    | '/members/$memberId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events/$eventId'
    | '/events/add'
    | '/members/add'
    | '/events'
    | '/members'
    | '/members/$memberId/edit'
    | '/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/events/$eventId'
    | '/events/add'
    | '/members/add'
    | '/events/'
    | '/members/'
    | '/members/$memberId/edit'
    | '/members/$memberId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsAddRoute: typeof EventsAddRoute
  MembersAddRoute: typeof MembersAddRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  MembersMemberIdEditRoute: typeof MembersMemberIdEditRoute
  MembersMemberIdIndexRoute: typeof MembersMemberIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/add': {
      id: '/members/add'
      path: '/members/add'
      fullPath: '/members/add'
      preLoaderRoute: typeof MembersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/add': {
      id: '/events/add'
      path: '/events/add'
      fullPath: '/events/add'
      preLoaderRoute: typeof EventsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId/': {
      id: '/members/$memberId/'
      path: '/members/$memberId'
      fullPath: '/members/$memberId/'
      preLoaderRoute: typeof MembersMemberIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId/edit': {
      id: '/members/$memberId/edit'
      path: '/members/$memberId/edit'
      fullPath: '/members/$memberId/edit'
      preLoaderRoute: typeof MembersMemberIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsAddRoute: EventsAddRoute,
  MembersAddRoute: MembersAddRoute,
  EventsIndexRoute: EventsIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  MembersMemberIdEditRoute: MembersMemberIdEditRoute,
  MembersMemberIdIndexRoute: MembersMemberIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
